# Generated by Django 5.2.4 on 2025-07-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(max_length=40)),
                ('guardian_mobile_no', models.CharField()),
                ('student_photo', models.ImageField(upload_to='')),
                ('student_aadhaar_number', models.CharField()),
                ('guardian_aadhaar_number', models.CharField()),
                ('permanent_address', models.CharField()),
                ('udisse_code', models.CharField()),
                ('admission_class', models.CharField()),
                ('previous_school', models.CharField()),
                ('current_address', models.CharField()),
            ],
        ),
    ]
