# Generated by Django 5.2.4 on 2025-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('profile_photo', models.ImageField(upload_to='')),
                ('address', models.CharField()),
                ('password', models.CharField()),
                ('creates_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
