# Generated by Django 5.2.4 on 2025-07-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvm', '0002_newuserregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserregistration',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='newuserregistration',
            name='mobile_no',
            field=models.CharField(default='xxxxx-xxxx'),
        ),
        migrations.AddField(
            model_name='newuserregistration',
            name='username',
            field=models.CharField(default=models.CharField(max_length=20)),
        ),
    ]
