# Generated by Django 5.2.4 on 2025-07-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvm', '0003_newuserregistration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserregistration',
            name='username',
            field=models.CharField(default='<django.db.models.fields.CharField>!@#'),
        ),
    ]
